name: Render Markdown to HTML

on: push

jobs:
  convert_via_pandoc:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Ensures the action can push changes

      - name: Convert README.md to HTML
        uses: docker://pandoc/core:3.5
        with:
          args: >-
            --standalone
            --include-in-header=copy-buttons.html
            --output=README.html
            README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.html
          git commit -m "Auto-generate README.html from GitHub Actions" || echo "No changes to commit"
          git push
